@startuml

skinparam class {
 BackgroundColor<<association>> Darkorange 
 BackgroundColor<<concept>>  Snow 
} 

package LandingGearSystem <<Folder>> {
	class LandingGear <<concept>>  {
		lgState : STRING
	}
	 object LG1 <<individual>> 
	LandingGear *-- LG1 : individualOf 

	LG1 : lgState = "lg_extended"
	class LandingSet <<concept>>  <<enumeration>>  {
	}
	 object LS1 <<individual>> 
	LandingSet *-- LS1 : individualOf 
	 object LS2 <<individual>> 
	LandingSet *-- LS2 : individualOf 
	 object LS3 <<individual>> 
	LandingSet *-- LS3 : individualOf 
	class Gear <<concept>>  {
	}
	 object G1 <<individual>> 
	Gear *-- G1 : individualOf 
	LandingSet "3" -- "1" LandingGear : > 
	 (LandingSet, LandingGear) .. LGofLS
	 class LGofLS <<association>>  <<variable>>  {
	}
	Gear "1" -- "1" LandingGear : > 
	 (Gear, LandingGear) .. LGofHD
	 class LGofHD <<association>>  <<variable>>  {
	}
}

@enduml
