package BSystem.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor mySystem__BehaviorDescriptor = new System__BehaviorDescriptor();
  private final BHDescriptor myPredicate__BehaviorDescriptor = new Predicate__BehaviorDescriptor();
  private final BHDescriptor myBSystemConcept__BehaviorDescriptor = new BSystemConcept__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt_a0g = concept;
    switch (index_846f5o_a0g.index(cncpt_a0g)) {
      case 0:
        return myBSystemConcept__BehaviorDescriptor;
      case 1:
        return myPredicate__BehaviorDescriptor;
      case 2:
        return mySystem__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0g = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L), MetaIdFactory.conceptId(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192432bL), MetaIdFactory.conceptId(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242e2L)).seal();
}
