package SysMLKaosDomainModeling.sandbox;

/*Generated by MPS */


public class map_DomainModel {
  public static void main(String[] args) {
    System.out.println("/* " + "lg_system_ref_0" + "\n* Author: SysML/KAOS Domain Model Parser\n* Creation time-millis: " + System.currentTimeMillis() + "\n*/");
    System.out.println("\nSYSTEM\n\t" + "lg_system_ref_0" + "\n");
    System.out.println("SETS\n");

    
    System.out.println("LandingGear");;


  }
}
