package Saturn.domain_models;

/*Generated by MPS */

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.FileNotFoundException;

public class map_DomainModel {

  public static String EVENT_B_MODELS_DIR_NAME = "Event_B_Models/";
  public static String EVENT_B_MODELS_FILE_EXTENSION = ".sys";
  public static String GRAPH_FILE_EXTENSION = ".puml";


  public static void main(String[] args) {
    File eventBModelFile = new File(new File(map_DomainModel.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_7" + EVENT_B_MODELS_FILE_EXTENSION);
    File graphFile = new File(new File(map_DomainModel.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_7" + GRAPH_FILE_EXTENSION);

    if (!(eventBModelFile.getParentFile().exists())) {
      eventBModelFile.getParentFile().mkdirs();
    }
    if (eventBModelFile.exists()) {
      eventBModelFile.delete();
      graphFile.delete();
    }
    try {
      eventBModelFile.createNewFile();
      graphFile.createNewFile();
    } catch (IOException e) {
      e.printStackTrace();
    }




    System.out.println("Path to Event-B Model File corresponding to " + "Saturn_7" + " : " + eventBModelFile);
    System.out.println("Path to graph File corresponding to " + "Saturn_7" + " : " + graphFile);

    try {
      PrintWriter pw = new PrintWriter(eventBModelFile);
      PrintWriter pwGraph = new PrintWriter(graphFile);



      pw.println("/* " + "Saturn_7" + "\n* Author: SysML/KAOS Domain Model Parser\n* Creation date: " + new SimpleDateFormat("dd/MM/yyyy").format(new Date()) + "\n*/");
      pw.println("\nSYSTEM\nSaturn_7");
      pw.println("");

      pw.println("\nSETS");
      pw.println("");

      pw.println("\nCONSTANTS");
      pw.println("");

      pw.println("\nVARIABLES");
      pw.println("In_Ch, Out_Ch");

      pw.println("\nPROPERTIES");
      pw.println("");

      pw.println("\nINVARIANT");
      pw.println("In_Ch : agents_in +-> TT &\nOut_Ch : agents_out +-> TT &\n//logical formula p1\n");

      pw.println("\nINITIALISATION");
      pw.println("");


      pw.println("\n\nEND");
      pw.close();

      pwGraph.println("@startuml");

      pwGraph.println("\nskinparam class {\n BackgroundColor<<association>> Darkorange \n BackgroundColor<<concept>>  Snow \n} ");



      pwGraph.println("");


      pwGraph.println("package " + "Saturn_7" + " <<Folder>> {");

      pwGraph.println("	class \"Saturn_4/agents_in\" as agents_in <<concept>> \n	class \"Saturn_4/agents_out\" as agents_out <<concept>> \n	class \"Saturn_4/TT\" as TT <<concept>> ");


      pwGraph.println("	agents_in \"*\" -- \"0..1\" TT : > \n	 (agents_in, TT) .. In_Ch\n	 class In_Ch <<association>>  <<variable>>  {\n	}\n	agents_out \"*\" -- \"0..1\" TT : > \n	 (agents_out, TT) .. Out_Ch\n	 class Out_Ch <<association>>  <<variable>>  {\n	}");

      pwGraph.println("}");

      pwGraph.println("");


      pwGraph.println("@enduml");
      pwGraph.close();


    } catch (FileNotFoundException e) {
      e.printStackTrace();
    }



  }
}
