package Saturn.domain_models;

/*Generated by MPS */

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.FileNotFoundException;

public class Saturn_6_handler {

  public static String EVENT_B_MODELS_DIR_NAME = "Event_B_Models/";
  public static String EVENT_B_MODELS_FILE_EXTENSION = ".sys";
  public static String GRAPH_FILE_EXTENSION = ".puml";


  public static void main(String[] args) {


    File eventBModelFile = new File(new File(Saturn_6_handler.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_6" + EVENT_B_MODELS_FILE_EXTENSION);
    File graphFile = new File(new File(Saturn_6_handler.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_6" + GRAPH_FILE_EXTENSION);

    if (!(eventBModelFile.getParentFile().exists())) {
      eventBModelFile.getParentFile().mkdirs();
    }
    if (eventBModelFile.exists()) {
      eventBModelFile.delete();
      graphFile.delete();
    }
    try {
      eventBModelFile.createNewFile();
      graphFile.createNewFile();
    } catch (IOException e) {
      e.printStackTrace();
    }




    System.out.println("Path to Event-B Model File corresponding to " + "Saturn_6" + " : " + eventBModelFile);
    System.out.println("Path to graph File corresponding to " + "Saturn_6" + " : " + graphFile);

    try {
      PrintWriter pw = new PrintWriter(eventBModelFile);
      PrintWriter pwGraph = new PrintWriter(graphFile);



      pw.println("/* " + "Saturn_6" + "\n* Author: SysML/KAOS Domain Model Parser\n* Creation date: " + new SimpleDateFormat("dd/MM/yyyy").format(new Date()) + "\n*/");
      pw.println("\nSYSTEM\nSaturn_6");
      pw.println("");

      pw.println("\nSETS");
      pw.println("Communication_Set={Broadcast, PointToPoint}");

      pw.println("\nCONSTANTS");
      pw.println("");

      pw.println("\nVARIABLES");
      pw.println("Communication");

      pw.println("\nPROPERTIES");
      pw.println("");

      pw.println("\nINVARIANT");
      pw.println("Communication : Communication_Set");

      pw.println("\nINITIALISATION");
      pw.println("Communication :: Communication_Set");


      pw.println("\n\nEND");
      pw.close();

      pwGraph.println("@startuml");

      pwGraph.println("\nskinparam class {\n BackgroundColor<<association>> Darkorange \n BackgroundColor<<concept>>  Snow \n} ");



      pwGraph.println("");


      pwGraph.println("package " + "Saturn_6" + " <<Folder>> {");

      pwGraph.println("	class Communication_Set <<concept>>  <<enumeration>>  {\n	}\n	 object Broadcast <<individual>> \n	Communication_Set *-- Broadcast : individualOf \n	 object PointToPoint <<individual>> \n	Communication_Set *-- PointToPoint : individualOf \n	 object Communication <<individual>>  <<variable>> \n	Communication_Set *-- Communication : individualOf ");


      pwGraph.println("");

      pwGraph.println("}");

      pwGraph.println("");


      pwGraph.println("@enduml");
      pwGraph.close();


    } catch (FileNotFoundException e) {
      e.printStackTrace();
    }



  }
}
