package Saturn.domain_models;

/*Generated by MPS */

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.FileNotFoundException;

public class Saturn_5_handler {

  public static String EVENT_B_MODELS_DIR_NAME = "Event_B_Models/";
  public static String EVENT_B_MODELS_FILE_EXTENSION = ".sys";
  public static String GRAPH_FILE_EXTENSION = ".puml";


  public static void main(String[] args) {


    File eventBModelFile = new File(new File(Saturn_5_handler.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_5" + EVENT_B_MODELS_FILE_EXTENSION);
    File graphFile = new File(new File(Saturn_5_handler.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "Saturn_5" + GRAPH_FILE_EXTENSION);

    if (!(eventBModelFile.getParentFile().exists())) {
      eventBModelFile.getParentFile().mkdirs();
    }
    if (eventBModelFile.exists()) {
      eventBModelFile.delete();
      graphFile.delete();
    }
    try {
      eventBModelFile.createNewFile();
      graphFile.createNewFile();
    } catch (IOException e) {
      e.printStackTrace();
    }




    System.out.println("Path to Event-B Model File corresponding to " + "Saturn_5" + " : " + eventBModelFile);
    System.out.println("Path to graph File corresponding to " + "Saturn_5" + " : " + graphFile);

    try {
      PrintWriter pw = new PrintWriter(eventBModelFile);
      PrintWriter pwGraph = new PrintWriter(graphFile);



      pw.println("/* " + "Saturn_5" + "\n* Author: SysML/KAOS Domain Model Parser\n* Creation date: " + new SimpleDateFormat("dd/MM/yyyy").format(new Date()) + "\n*/");
      pw.println("\nREFINEMENT\nSaturn_5");
      pw.println("REFINES\nSaturn_4");

      pw.println("\nSETS");
      pw.println("Implementation_Set={Distributed, Centralised}");

      pw.println("\nCONSTANTS");
      pw.println("");

      pw.println("\nVARIABLES");
      pw.println("Implementation");

      pw.println("\nPROPERTIES");
      pw.println("");

      pw.println("\nINVARIANT");
      pw.println("Implementation : Implementation_Set");

      pw.println("\nINITIALISATION");
      pw.println("Implementation :: Implementation_Set");


      pw.println("\n\nEND");
      pw.close();

      pwGraph.println("@startuml");

      pwGraph.println("\nskinparam class {\n BackgroundColor<<association>> Darkorange \n BackgroundColor<<concept>>  Snow \n} ");



      pwGraph.println("package Saturn_4  <<Folder>> {\n}");


      pwGraph.println("package " + "Saturn_5" + " <<Folder>> {");

      pwGraph.println("	class Implementation_Set <<concept>>  <<enumeration>>  {\n	}\n	 object Distributed <<individual>> \n	Implementation_Set *-- Distributed : individualOf \n	 object Centralised <<individual>> \n	Implementation_Set *-- Centralised : individualOf \n	 object Implementation <<individual>>  <<variable>> \n	Implementation_Set *-- Implementation : individualOf ");


      pwGraph.println("");

      pwGraph.println("}");

      pwGraph.println("Saturn_4 <|-- Saturn_5");


      pwGraph.println("@enduml");
      pwGraph.close();


    } catch (FileNotFoundException e) {
      e.printStackTrace();
    }



  }
}
