package BSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a4b0o = new IconResource("TextIcon_2.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a01b0o = new IconResource("TextIcon_1.png", IconContainer.class);
}
