package BSystem.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptBComment = createDescriptorForBComment();
  /*package*/ final ConceptDescriptor myConceptBSystemConcept = createDescriptorForBSystemConcept();
  /*package*/ final ConceptDescriptor myConceptConstant = createDescriptorForConstant();
  /*package*/ final ConceptDescriptor myConceptContext = createDescriptorForContext();
  /*package*/ final ConceptDescriptor myConceptEnumeratedSet = createDescriptorForEnumeratedSet();
  /*package*/ final ConceptDescriptor myConceptInvariant = createDescriptorForInvariant();
  /*package*/ final ConceptDescriptor myConceptPredicate = createDescriptorForPredicate();
  /*package*/ final ConceptDescriptor myConceptProperty = createDescriptorForProperty();
  /*package*/ final ConceptDescriptor myConceptSet = createDescriptorForSet();
  /*package*/ final ConceptDescriptor myConceptSystem = createDescriptorForSystem();
  /*package*/ final ConceptDescriptor myConceptTerm = createDescriptorForTerm();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptBComment, myConceptBSystemConcept, myConceptConstant, myConceptContext, myConceptEnumeratedSet, myConceptInvariant, myConceptPredicate, myConceptProperty, myConceptSet, myConceptSystem, myConceptTerm, myConceptVariable);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.BComment:
        return myConceptBComment;
      case LanguageConceptSwitch.BSystemConcept:
        return myConceptBSystemConcept;
      case LanguageConceptSwitch.Constant:
        return myConceptConstant;
      case LanguageConceptSwitch.Context:
        return myConceptContext;
      case LanguageConceptSwitch.EnumeratedSet:
        return myConceptEnumeratedSet;
      case LanguageConceptSwitch.Invariant:
        return myConceptInvariant;
      case LanguageConceptSwitch.Predicate:
        return myConceptPredicate;
      case LanguageConceptSwitch.Property:
        return myConceptProperty;
      case LanguageConceptSwitch.Set:
        return myConceptSet;
      case LanguageConceptSwitch.System:
        return myConceptSystem;
      case LanguageConceptSwitch.Term:
        return myConceptTerm;
      case LanguageConceptSwitch.Variable:
        return myConceptVariable;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Action", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433cL);
    b.class_(false, false, false);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405948");
    b.prop("formula", 0x47342804c192433fL, "5130769876374405951");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "BComment", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x5b61b7c2a5e6d100L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/6584746176827281664");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBSystemConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405939");
    b.aggregate("comment", 0x5b61b7c2a5e6dd2aL).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x5b61b7c2a5e6d100L).optional(true).ordered(true).multiple(false).origin("6584746176827284778").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForConstant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Constant", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924326L);
    b.class_(false, false, false);
    b.super_("BSystem.structure.Term", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433aL);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405926");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContext() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Context", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242c6L);
    b.class_(false, false, true);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405830");
    b.associate("extends", 0x47342804c192436bL).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242c6L).optional(true).origin("5130769876374405995").done();
    b.aggregate("SETS", 0x47342804c1924341L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924302L).optional(true).ordered(true).multiple(true).origin("5130769876374405953").done();
    b.aggregate("CONSTANTS", 0x47342804c1924343L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924326L).optional(true).ordered(true).multiple(true).origin("5130769876374405955").done();
    b.aggregate("PROPERTIES", 0x47342804c1924346L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924338L).optional(true).ordered(true).multiple(true).origin("5130769876374405958").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnumeratedSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "EnumeratedSet", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924325L);
    b.class_(false, false, false);
    b.super_("BSystem.structure.Set", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924302L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405925");
    b.aggregate("elements", 0x47342804c1924329L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924326L).optional(false).ordered(true).multiple(true).origin("5130769876374405929").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInvariant() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Invariant", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924339L);
    b.class_(false, false, false);
    b.super_("BSystem.structure.Predicate", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192432bL);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405945");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPredicate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Predicate", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192432bL);
    b.class_(false, false, false);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405931");
    b.prop("formula", 0x47342804c192432eL, "5130769876374405934");
    b.prop("isTheorem", 0x47342804c1924330L, "5130769876374405936");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProperty() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Property", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924338L);
    b.class_(false, false, false);
    b.super_("BSystem.structure.Predicate", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192432bL);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405944");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Set", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924302L);
    b.class_(false, false, false);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405890");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSystem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "System", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242e2L);
    b.class_(false, false, true);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405858");
    b.prop("title", 0x157fb89c59aabed5L, "1549159778497511125");
    b.associate("sees", 0x47342804c1924323L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242c6L).optional(true).origin("5130769876374405923").done();
    b.associate("refines", 0x47342804c1a3c401L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c19242e2L).optional(true).origin("5130769876375553025").done();
    b.aggregate("SETS", 0x47342804c192434aL).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924302L).optional(true).ordered(true).multiple(true).origin("5130769876374405962").done();
    b.aggregate("CONSTANTS", 0x47342804c192434dL).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924326L).optional(true).ordered(true).multiple(true).origin("5130769876374405965").done();
    b.aggregate("PROPERTIES", 0x47342804c1924351L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924338L).optional(true).ordered(true).multiple(true).origin("5130769876374405969").done();
    b.aggregate("VARIABLES", 0x47342804c1924356L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433bL).optional(true).ordered(true).multiple(true).origin("5130769876374405974").done();
    b.aggregate("INVARIANTS", 0x47342804c192435cL).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924339L).optional(true).ordered(true).multiple(true).origin("5130769876374405980").done();
    b.aggregate("INITIALISATION", 0x47342804c1924363L).target(0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433cL).optional(true).ordered(true).multiple(true).origin("5130769876374405987").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTerm() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Term", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433aL);
    b.class_(false, false, false);
    b.super_("BSystem.structure.BSystemConcept", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c1924333L);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405946");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BSystem", "Variable", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433bL);
    b.class_(false, false, false);
    b.super_("BSystem.structure.Term", 0xbe9c247ddd744e87L, 0x98fb8757587ebb62L, 0x47342804c192433aL);
    b.origin("r:70b077f4-d004-4cf6-a2c8-7d579d59d51a(BSystem.structure)/5130769876374405947");
    return b.create();
  }
}
