package ABZ18.ERTMS;

/*Generated by MPS */

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.FileNotFoundException;

public class map_DomainModel {
  public static String EVENT_B_MODELS_DIR_NAME = "Event_B_Models/";
  public static String EVENT_B_MODELS_FILE_EXTENSION = ".sys";

  public static void main(String[] args) {
    File eventBModelFile = new File(new File(map_DomainModel.class.getProtectionDomain().getCodeSource().getLocation().getFile()).getParentFile(), EVENT_B_MODELS_DIR_NAME + "ERTMS_ref_2" + EVENT_B_MODELS_FILE_EXTENSION);
    if (!(eventBModelFile.getParentFile().exists())) {
      eventBModelFile.getParentFile().mkdirs();
    }
    if (eventBModelFile.exists()) {
      eventBModelFile.delete();
    }
    try {
      eventBModelFile.createNewFile();
    } catch (IOException e) {
      e.printStackTrace();
    }



    System.out.println("Path to Event-B Model File corresponding to " + "ERTMS_ref_2" + " : " + eventBModelFile);
    try {
      PrintWriter pw = new PrintWriter(eventBModelFile);


      pw.println("/* " + "ERTMS_ref_2" + "\n* Author: SysML/KAOS Domain Model Parser\n* Creation date: " + new SimpleDateFormat("dd/MM/yyyy").format(new Date()) + "\n*/");
      pw.println("\nREFINEMENT\nERTMS_ref_2");
      pw.println("REFINES\nERTMS_ref_1");

      pw.println("\nSETS");
      pw.println("FS_MA; TIMER; MUTE_TIMER");

      pw.println("\nCONSTANTS");
      pw.println("WAITING_TIMER, T_FS_MA_IS_DEFINED_ON, T_TRAIN_FS_MA");

      pw.println("\nVARIABLES");
      pw.println("X_FS_MA, FS_MA_IS_DEFINED_ON, TRAIN_FS_MA");

      pw.println("\nPROPERTIES");
      pw.println(" &\nWAITING_TIMER <: TIMER &\nT_FS_MA_IS_DEFINED_ON = FS_MA <-> VIRTUAL_SUB_SECTION &\nT_TRAIN_FS_MA = TRAIN <-> FS_MA");

      pw.println("\nINVARIANT");
      pw.println("X_FS_MA <: FS_MA &\nFS_MA_IS_DEFINED_ON : T_FS_MA_IS_DEFINED_ON &\n!xx. (xx : dom(FS_MA_IS_DEFINED_ON) => card(FS_MA_IS_DEFINED_ON[{xx}]) : 0..1) &\n!xx. (xx : ran(FS_MA_IS_DEFINED_ON) => card(FS_MA_IS_DEFINED_ON~[{xx}]) >= 1) &\nTRAIN_FS_MA : T_TRAIN_FS_MA &\n!xx. (xx : ran(TRAIN_FS_MA) => card(TRAIN_FS_MA~[{xx}]) : 0..1) &\n!xx. (xx : dom(TRAIN_FS_MA) => card(TRAIN_FS_MA[{xx}]) : 0..1)");

      pw.println("\nINITIALISATION");
      pw.println("");


      pw.println("\n\nEND");
      pw.close();

    } catch (FileNotFoundException e) {
      e.printStackTrace();
    }



  }
}
