package SysMLKaosDomainModeling.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Atom = 0;
  public static final int Attribute = 1;
  public static final int AttributeMaplet = 2;
  public static final int Body = 3;
  public static final int Cardinality = 4;
  public static final int Concept = 5;
  public static final int CustomDataSet = 6;
  public static final int DataSet = 7;
  public static final int DataValue = 8;
  public static final int DefaultDataSet = 9;
  public static final int DomainCardinality = 10;
  public static final int DomainModel = 11;
  public static final int EnumeratedDataSet = 12;
  public static final int Head = 13;
  public static final int Individual = 14;
  public static final int Predicate = 15;
  public static final int RangeCardinality = 16;
  public static final int Relation = 17;
  public static final int RelationMaplet = 18;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9715e310dbcb448eL, 0x93035bfaafdcf84dL);
    builder.put(0x506f58146949816dL, Atom);
    builder.put(0x506f58146949819aL, Attribute);
    builder.put(0x506f5814694981fbL, AttributeMaplet);
    builder.put(0x506f581469498151L, Body);
    builder.put(0x506f5814694982a3L, Cardinality);
    builder.put(0x506f581469497f85L, Concept);
    builder.put(0x506f581469498071L, CustomDataSet);
    builder.put(0x506f581469497faaL, DataSet);
    builder.put(0x506f5814694980ebL, DataValue);
    builder.put(0x506f581469497fc9L, DefaultDataSet);
    builder.put(0x506f5814694982c7L, DomainCardinality);
    builder.put(0x506f581469497d02L, DomainModel);
    builder.put(0x506f5814694980ccL, EnumeratedDataSet);
    builder.put(0x506f581469498132L, Head);
    builder.put(0x506f58146949821aL, Individual);
    builder.put(0x506f581469498113L, Predicate);
    builder.put(0x506f5814694982e3L, RangeCardinality);
    builder.put(0x506f58146949824cL, Relation);
    builder.put(0x506f581469498373L, RelationMaplet);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
